<article class="post-container {{ $post->body_classes }}"
    id="post-{{ $details['board_uri'] }}-{{ $details['board_id'] }}"
    data-widget="post"
    data-post_id="{{ $details['post_id'] }}"
    data-board_uri="{{ $details['board_uri'] }}"
    data-board_id="{{ $details['board_id'] }}"
    data-reply-to-board-id="{{ $reply_to ? $details['reply_to_board_id'] : null }}"
    data-created-at="{{ $post->created_at->timestamp }}"
    data-updated-at="{{ $post->updated_at->timestamp }}"
    data-bumped-last="{{ $post->global_bumped_last->timestamp }}"
    data-capcode="{{ isset($details['capcode_capcode']) ? $details['capcode_capcode'] : '' }}"
>
